/**
 * India geo helpers.
 *
 * Google Places is the authoritative source when an API key is configured
 * (see `AddressAutocomplete`). This module is the offline fallback so the
 * booking flow stays fully usable without a key — and it also backs the
 * rate-card zone pickers, which must work server-side regardless.
 *
 * Resolution order: 3-digit district prefix (city + state) -> 2-digit postal
 * circle (state only). Everything it returns is a *suggestion*; every field it
 * fills stays editable in the UI.
 */

export const INDIAN_STATES = [
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export type IndianState = (typeof INDIAN_STATES)[number];

/** Postal circle by 2-digit prefix — state-level fallback. */
const PIN2_STATE: Record<string, IndianState> = {
  "11": "Delhi",
  "12": "Haryana",
  "13": "Haryana",
  "14": "Punjab",
  "15": "Punjab",
  "16": "Punjab",
  "17": "Himachal Pradesh",
  "18": "Jammu & Kashmir",
  "19": "Jammu & Kashmir",
  "20": "Uttar Pradesh",
  "21": "Uttar Pradesh",
  "22": "Uttar Pradesh",
  "23": "Uttar Pradesh",
  "24": "Uttar Pradesh",
  "25": "Uttar Pradesh",
  "26": "Uttar Pradesh",
  "27": "Uttar Pradesh",
  "28": "Uttar Pradesh",
  "30": "Rajasthan",
  "31": "Rajasthan",
  "32": "Rajasthan",
  "33": "Rajasthan",
  "34": "Rajasthan",
  "36": "Gujarat",
  "37": "Gujarat",
  "38": "Gujarat",
  "39": "Gujarat",
  "40": "Maharashtra",
  "41": "Maharashtra",
  "42": "Maharashtra",
  "43": "Maharashtra",
  "44": "Maharashtra",
  "45": "Madhya Pradesh",
  "46": "Madhya Pradesh",
  "47": "Madhya Pradesh",
  "48": "Madhya Pradesh",
  "49": "Chhattisgarh",
  "50": "Telangana",
  "51": "Andhra Pradesh",
  "52": "Andhra Pradesh",
  "53": "Andhra Pradesh",
  "56": "Karnataka",
  "57": "Karnataka",
  "58": "Karnataka",
  "59": "Karnataka",
  "60": "Tamil Nadu",
  "61": "Tamil Nadu",
  "62": "Tamil Nadu",
  "63": "Tamil Nadu",
  "64": "Tamil Nadu",
  "65": "Tamil Nadu",
  "66": "Tamil Nadu",
  "67": "Kerala",
  "68": "Kerala",
  "69": "Kerala",
  "70": "West Bengal",
  "71": "West Bengal",
  "72": "West Bengal",
  "73": "West Bengal",
  "74": "West Bengal",
  "75": "Odisha",
  "76": "Odisha",
  "77": "Odisha",
  "78": "Assam",
  "79": "Tripura",
  "80": "Bihar",
  "81": "Bihar",
  "82": "Jharkhand",
  "83": "Jharkhand",
  "84": "Bihar",
  "85": "Bihar",
};

/**
 * District/city by 3-digit prefix. Covers the commercially significant lanes;
 * anything not listed degrades to the state-level answer above.
 */
const PIN3_CITY: Record<string, [string, IndianState]> = {
  // Delhi NCR
  "110": ["Delhi", "Delhi"],
  "201": ["Ghaziabad", "Uttar Pradesh"],
  "203": ["Bulandshahr", "Uttar Pradesh"],
  "121": ["Faridabad", "Haryana"],
  "122": ["Gurugram", "Haryana"],
  "123": ["Rewari", "Haryana"],
  "124": ["Rohtak", "Haryana"],
  "125": ["Hisar", "Haryana"],
  "126": ["Jind", "Haryana"],
  "127": ["Bhiwani", "Haryana"],
  "131": ["Sonipat", "Haryana"],
  "132": ["Karnal", "Haryana"],
  "133": ["Ambala", "Haryana"],
  "134": ["Panchkula", "Haryana"],
  "135": ["Yamunanagar", "Haryana"],
  "136": ["Kurukshetra", "Haryana"],
  // Punjab / Chandigarh / HP / J&K
  "140": ["Rupnagar", "Punjab"],
  "141": ["Ludhiana", "Punjab"],
  "142": ["Moga", "Punjab"],
  "143": ["Amritsar", "Punjab"],
  "144": ["Jalandhar", "Punjab"],
  "145": ["Pathankot", "Punjab"],
  "146": ["Hoshiarpur", "Punjab"],
  "147": ["Patiala", "Punjab"],
  "148": ["Sangrur", "Punjab"],
  "151": ["Bathinda", "Punjab"],
  "152": ["Ferozepur", "Punjab"],
  "160": ["Chandigarh", "Chandigarh"],
  "171": ["Shimla", "Himachal Pradesh"],
  "173": ["Solan", "Himachal Pradesh"],
  "174": ["Bilaspur", "Himachal Pradesh"],
  "175": ["Mandi", "Himachal Pradesh"],
  "176": ["Kangra", "Himachal Pradesh"],
  "177": ["Una", "Himachal Pradesh"],
  "180": ["Jammu", "Jammu & Kashmir"],
  "190": ["Srinagar", "Jammu & Kashmir"],
  "194": ["Leh", "Ladakh"],
  // Uttar Pradesh / Uttarakhand
  "202": ["Aligarh", "Uttar Pradesh"],
  "204": ["Hathras", "Uttar Pradesh"],
  "205": ["Mainpuri", "Uttar Pradesh"],
  "206": ["Etawah", "Uttar Pradesh"],
  "207": ["Etah", "Uttar Pradesh"],
  "208": ["Kanpur", "Uttar Pradesh"],
  "209": ["Kanpur Dehat", "Uttar Pradesh"],
  "210": ["Banda", "Uttar Pradesh"],
  "211": ["Prayagraj", "Uttar Pradesh"],
  "212": ["Kaushambi", "Uttar Pradesh"],
  "221": ["Varanasi", "Uttar Pradesh"],
  "222": ["Jaunpur", "Uttar Pradesh"],
  "223": ["Azamgarh", "Uttar Pradesh"],
  "224": ["Ayodhya", "Uttar Pradesh"],
  "225": ["Barabanki", "Uttar Pradesh"],
  "226": ["Lucknow", "Uttar Pradesh"],
  "227": ["Lucknow", "Uttar Pradesh"],
  "228": ["Sultanpur", "Uttar Pradesh"],
  "229": ["Raebareli", "Uttar Pradesh"],
  "231": ["Mirzapur", "Uttar Pradesh"],
  "232": ["Ghazipur", "Uttar Pradesh"],
  "233": ["Ballia", "Uttar Pradesh"],
  "241": ["Hardoi", "Uttar Pradesh"],
  "242": ["Shahjahanpur", "Uttar Pradesh"],
  "243": ["Bareilly", "Uttar Pradesh"],
  "244": ["Moradabad", "Uttar Pradesh"],
  "245": ["Hapur", "Uttar Pradesh"],
  "246": ["Pauri Garhwal", "Uttarakhand"],
  "247": ["Saharanpur", "Uttar Pradesh"],
  "248": ["Dehradun", "Uttarakhand"],
  "249": ["Haridwar", "Uttarakhand"],
  "250": ["Meerut", "Uttar Pradesh"],
  "251": ["Muzaffarnagar", "Uttar Pradesh"],
  "261": ["Sitapur", "Uttar Pradesh"],
  "262": ["Lakhimpur Kheri", "Uttar Pradesh"],
  "263": ["Nainital", "Uttarakhand"],
  "271": ["Gonda", "Uttar Pradesh"],
  "272": ["Basti", "Uttar Pradesh"],
  "273": ["Gorakhpur", "Uttar Pradesh"],
  "274": ["Deoria", "Uttar Pradesh"],
  "276": ["Mau", "Uttar Pradesh"],
  "281": ["Mathura", "Uttar Pradesh"],
  "282": ["Agra", "Uttar Pradesh"],
  "283": ["Firozabad", "Uttar Pradesh"],
  "284": ["Jhansi", "Uttar Pradesh"],
  "285": ["Jalaun", "Uttar Pradesh"],
  // Rajasthan
  "301": ["Alwar", "Rajasthan"],
  "302": ["Jaipur", "Rajasthan"],
  "303": ["Jaipur", "Rajasthan"],
  "304": ["Tonk", "Rajasthan"],
  "305": ["Ajmer", "Rajasthan"],
  "306": ["Pali", "Rajasthan"],
  "307": ["Sirohi", "Rajasthan"],
  "311": ["Bhilwara", "Rajasthan"],
  "312": ["Chittorgarh", "Rajasthan"],
  "313": ["Udaipur", "Rajasthan"],
  "321": ["Bharatpur", "Rajasthan"],
  "322": ["Sawai Madhopur", "Rajasthan"],
  "324": ["Kota", "Rajasthan"],
  "326": ["Jhalawar", "Rajasthan"],
  "327": ["Banswara", "Rajasthan"],
  "331": ["Churu", "Rajasthan"],
  "332": ["Sikar", "Rajasthan"],
  "333": ["Jhunjhunu", "Rajasthan"],
  "334": ["Bikaner", "Rajasthan"],
  "335": ["Sri Ganganagar", "Rajasthan"],
  "341": ["Nagaur", "Rajasthan"],
  "342": ["Jodhpur", "Rajasthan"],
  "344": ["Barmer", "Rajasthan"],
  "345": ["Jaisalmer", "Rajasthan"],
  // Gujarat
  "360": ["Rajkot", "Gujarat"],
  "361": ["Jamnagar", "Gujarat"],
  "362": ["Junagadh", "Gujarat"],
  "363": ["Surendranagar", "Gujarat"],
  "364": ["Bhavnagar", "Gujarat"],
  "365": ["Amreli", "Gujarat"],
  "370": ["Kutch", "Gujarat"],
  "380": ["Ahmedabad", "Gujarat"],
  "382": ["Gandhinagar", "Gujarat"],
  "383": ["Sabarkantha", "Gujarat"],
  "384": ["Mehsana", "Gujarat"],
  "385": ["Banaskantha", "Gujarat"],
  "387": ["Kheda", "Gujarat"],
  "388": ["Anand", "Gujarat"],
  "389": ["Godhra", "Gujarat"],
  "390": ["Vadodara", "Gujarat"],
  "391": ["Vadodara", "Gujarat"],
  "392": ["Bharuch", "Gujarat"],
  "393": ["Bharuch", "Gujarat"],
  "394": ["Surat", "Gujarat"],
  "395": ["Surat", "Gujarat"],
  "396": ["Valsad", "Gujarat"],
  // Maharashtra / Goa
  "400": ["Mumbai", "Maharashtra"],
  "401": ["Palghar", "Maharashtra"],
  "402": ["Raigad", "Maharashtra"],
  "403": ["Panaji", "Goa"],
  "410": ["Navi Mumbai", "Maharashtra"],
  "411": ["Pune", "Maharashtra"],
  "412": ["Pune", "Maharashtra"],
  "413": ["Solapur", "Maharashtra"],
  "414": ["Ahmednagar", "Maharashtra"],
  "415": ["Satara", "Maharashtra"],
  "416": ["Kolhapur", "Maharashtra"],
  "421": ["Thane", "Maharashtra"],
  "422": ["Nashik", "Maharashtra"],
  "423": ["Nashik", "Maharashtra"],
  "424": ["Dhule", "Maharashtra"],
  "425": ["Jalgaon", "Maharashtra"],
  "431": ["Chhatrapati Sambhajinagar", "Maharashtra"],
  "440": ["Nagpur", "Maharashtra"],
  "441": ["Nagpur", "Maharashtra"],
  "442": ["Chandrapur", "Maharashtra"],
  "443": ["Buldhana", "Maharashtra"],
  "444": ["Akola", "Maharashtra"],
  "445": ["Yavatmal", "Maharashtra"],
  // Madhya Pradesh / Chhattisgarh
  "450": ["Khandwa", "Madhya Pradesh"],
  "451": ["Khargone", "Madhya Pradesh"],
  "452": ["Indore", "Madhya Pradesh"],
  "453": ["Indore", "Madhya Pradesh"],
  "455": ["Dewas", "Madhya Pradesh"],
  "456": ["Ujjain", "Madhya Pradesh"],
  "457": ["Ratlam", "Madhya Pradesh"],
  "458": ["Mandsaur", "Madhya Pradesh"],
  "461": ["Hoshangabad", "Madhya Pradesh"],
  "462": ["Bhopal", "Madhya Pradesh"],
  "464": ["Vidisha", "Madhya Pradesh"],
  "465": ["Rajgarh", "Madhya Pradesh"],
  "466": ["Sehore", "Madhya Pradesh"],
  "470": ["Sagar", "Madhya Pradesh"],
  "472": ["Tikamgarh", "Madhya Pradesh"],
  "473": ["Guna", "Madhya Pradesh"],
  "474": ["Gwalior", "Madhya Pradesh"],
  "475": ["Bhind", "Madhya Pradesh"],
  "476": ["Morena", "Madhya Pradesh"],
  "480": ["Chhindwara", "Madhya Pradesh"],
  "481": ["Balaghat", "Madhya Pradesh"],
  "482": ["Jabalpur", "Madhya Pradesh"],
  "483": ["Katni", "Madhya Pradesh"],
  "484": ["Anuppur", "Madhya Pradesh"],
  "485": ["Satna", "Madhya Pradesh"],
  "486": ["Rewa", "Madhya Pradesh"],
  "490": ["Durg", "Chhattisgarh"],
  "491": ["Rajnandgaon", "Chhattisgarh"],
  "492": ["Raipur", "Chhattisgarh"],
  "493": ["Raipur", "Chhattisgarh"],
  "494": ["Jagdalpur", "Chhattisgarh"],
  "495": ["Bilaspur", "Chhattisgarh"],
  "496": ["Raigarh", "Chhattisgarh"],
  "497": ["Korea", "Chhattisgarh"],
  // Telangana / Andhra Pradesh
  "500": ["Hyderabad", "Telangana"],
  "501": ["Hyderabad", "Telangana"],
  "502": ["Medak", "Telangana"],
  "503": ["Nizamabad", "Telangana"],
  "504": ["Adilabad", "Telangana"],
  "505": ["Karimnagar", "Telangana"],
  "506": ["Warangal", "Telangana"],
  "507": ["Khammam", "Telangana"],
  "508": ["Nalgonda", "Telangana"],
  "509": ["Mahbubnagar", "Telangana"],
  "515": ["Anantapur", "Andhra Pradesh"],
  "516": ["Kadapa", "Andhra Pradesh"],
  "517": ["Tirupati", "Andhra Pradesh"],
  "518": ["Kurnool", "Andhra Pradesh"],
  "520": ["Vijayawada", "Andhra Pradesh"],
  "521": ["Krishna", "Andhra Pradesh"],
  "522": ["Guntur", "Andhra Pradesh"],
  "523": ["Ongole", "Andhra Pradesh"],
  "524": ["Nellore", "Andhra Pradesh"],
  "530": ["Visakhapatnam", "Andhra Pradesh"],
  "531": ["Visakhapatnam", "Andhra Pradesh"],
  "532": ["Srikakulam", "Andhra Pradesh"],
  "533": ["Kakinada", "Andhra Pradesh"],
  "534": ["Bhimavaram", "Andhra Pradesh"],
  "535": ["Vizianagaram", "Andhra Pradesh"],
  // Karnataka
  "560": ["Bengaluru", "Karnataka"],
  "561": ["Bengaluru Rural", "Karnataka"],
  "562": ["Bengaluru Rural", "Karnataka"],
  "563": ["Kolar", "Karnataka"],
  "570": ["Mysuru", "Karnataka"],
  "571": ["Mandya", "Karnataka"],
  "572": ["Tumakuru", "Karnataka"],
  "573": ["Hassan", "Karnataka"],
  "574": ["Mangaluru", "Karnataka"],
  "575": ["Mangaluru", "Karnataka"],
  "576": ["Udupi", "Karnataka"],
  "577": ["Davanagere", "Karnataka"],
  "580": ["Hubballi", "Karnataka"],
  "581": ["Haveri", "Karnataka"],
  "582": ["Gadag", "Karnataka"],
  "583": ["Ballari", "Karnataka"],
  "584": ["Raichur", "Karnataka"],
  "585": ["Kalaburagi", "Karnataka"],
  "586": ["Vijayapura", "Karnataka"],
  "587": ["Bagalkot", "Karnataka"],
  "590": ["Belagavi", "Karnataka"],
  "591": ["Belagavi", "Karnataka"],
  // Tamil Nadu / Puducherry
  "600": ["Chennai", "Tamil Nadu"],
  "601": ["Tiruvallur", "Tamil Nadu"],
  "602": ["Tiruvallur", "Tamil Nadu"],
  "603": ["Chengalpattu", "Tamil Nadu"],
  "604": ["Tiruvannamalai", "Tamil Nadu"],
  "605": ["Puducherry", "Puducherry"],
  "606": ["Cuddalore", "Tamil Nadu"],
  "607": ["Cuddalore", "Tamil Nadu"],
  "608": ["Chidambaram", "Tamil Nadu"],
  "609": ["Karaikal", "Puducherry"],
  "610": ["Tiruvarur", "Tamil Nadu"],
  "612": ["Thanjavur", "Tamil Nadu"],
  "613": ["Thanjavur", "Tamil Nadu"],
  "614": ["Pudukkottai", "Tamil Nadu"],
  "620": ["Tiruchirappalli", "Tamil Nadu"],
  "621": ["Perambalur", "Tamil Nadu"],
  "623": ["Ramanathapuram", "Tamil Nadu"],
  "624": ["Dindigul", "Tamil Nadu"],
  "625": ["Madurai", "Tamil Nadu"],
  "626": ["Virudhunagar", "Tamil Nadu"],
  "627": ["Tirunelveli", "Tamil Nadu"],
  "628": ["Thoothukudi", "Tamil Nadu"],
  "629": ["Kanyakumari", "Tamil Nadu"],
  "630": ["Sivaganga", "Tamil Nadu"],
  "635": ["Krishnagiri", "Tamil Nadu"],
  "636": ["Salem", "Tamil Nadu"],
  "637": ["Namakkal", "Tamil Nadu"],
  "638": ["Erode", "Tamil Nadu"],
  "639": ["Karur", "Tamil Nadu"],
  "641": ["Coimbatore", "Tamil Nadu"],
  "642": ["Pollachi", "Tamil Nadu"],
  "643": ["Nilgiris", "Tamil Nadu"],
  // Kerala / Lakshadweep
  "670": ["Kannur", "Kerala"],
  "671": ["Kasaragod", "Kerala"],
  "673": ["Kozhikode", "Kerala"],
  "676": ["Malappuram", "Kerala"],
  "678": ["Palakkad", "Kerala"],
  "679": ["Palakkad", "Kerala"],
  "680": ["Thrissur", "Kerala"],
  "682": ["Kochi", "Kerala"],
  "683": ["Ernakulam", "Kerala"],
  "685": ["Idukki", "Kerala"],
  "686": ["Kottayam", "Kerala"],
  "688": ["Alappuzha", "Kerala"],
  "689": ["Pathanamthitta", "Kerala"],
  "690": ["Kollam", "Kerala"],
  "691": ["Kollam", "Kerala"],
  "695": ["Thiruvananthapuram", "Kerala"],
  // West Bengal / Sikkim
  "700": ["Kolkata", "West Bengal"],
  "711": ["Howrah", "West Bengal"],
  "712": ["Hooghly", "West Bengal"],
  "713": ["Durgapur", "West Bengal"],
  "721": ["Kharagpur", "West Bengal"],
  "722": ["Bankura", "West Bengal"],
  "723": ["Purulia", "West Bengal"],
  "731": ["Birbhum", "West Bengal"],
  "732": ["Malda", "West Bengal"],
  "733": ["Uttar Dinajpur", "West Bengal"],
  "734": ["Siliguri", "West Bengal"],
  "735": ["Jalpaiguri", "West Bengal"],
  "736": ["Cooch Behar", "West Bengal"],
  "737": ["Gangtok", "Sikkim"],
  "741": ["Nadia", "West Bengal"],
  "742": ["Murshidabad", "West Bengal"],
  "743": ["North 24 Parganas", "West Bengal"],
  "744": ["Port Blair", "Andaman & Nicobar Islands"],
  // Odisha
  "751": ["Bhubaneswar", "Odisha"],
  "752": ["Puri", "Odisha"],
  "753": ["Cuttack", "Odisha"],
  "754": ["Cuttack", "Odisha"],
  "755": ["Jajpur", "Odisha"],
  "756": ["Balasore", "Odisha"],
  "757": ["Mayurbhanj", "Odisha"],
  "758": ["Keonjhar", "Odisha"],
  "759": ["Dhenkanal", "Odisha"],
  "760": ["Berhampur", "Odisha"],
  "761": ["Ganjam", "Odisha"],
  "764": ["Koraput", "Odisha"],
  "765": ["Rayagada", "Odisha"],
  "766": ["Kalahandi", "Odisha"],
  "768": ["Sambalpur", "Odisha"],
  "769": ["Rourkela", "Odisha"],
  // North East
  "781": ["Guwahati", "Assam"],
  "782": ["Nagaon", "Assam"],
  "783": ["Goalpara", "Assam"],
  "784": ["Tezpur", "Assam"],
  "785": ["Jorhat", "Assam"],
  "786": ["Dibrugarh", "Assam"],
  "787": ["Lakhimpur", "Assam"],
  "788": ["Silchar", "Assam"],
  "790": ["Bomdila", "Arunachal Pradesh"],
  "791": ["Itanagar", "Arunachal Pradesh"],
  "792": ["Tezu", "Arunachal Pradesh"],
  "793": ["Shillong", "Meghalaya"],
  "794": ["Tura", "Meghalaya"],
  "795": ["Imphal", "Manipur"],
  "796": ["Aizawl", "Mizoram"],
  "797": ["Kohima", "Nagaland"],
  "798": ["Mokokchung", "Nagaland"],
  "799": ["Agartala", "Tripura"],
  // Bihar / Jharkhand
  "800": ["Patna", "Bihar"],
  "801": ["Patna", "Bihar"],
  "802": ["Bhojpur", "Bihar"],
  "803": ["Nalanda", "Bihar"],
  "804": ["Patna", "Bihar"],
  "811": ["Munger", "Bihar"],
  "812": ["Bhagalpur", "Bihar"],
  "813": ["Banka", "Bihar"],
  "814": ["Deoghar", "Jharkhand"],
  "815": ["Giridih", "Jharkhand"],
  "816": ["Dumka", "Jharkhand"],
  "821": ["Sasaram", "Bihar"],
  "822": ["Daltonganj", "Jharkhand"],
  "823": ["Gaya", "Bihar"],
  "824": ["Aurangabad", "Bihar"],
  "825": ["Hazaribagh", "Jharkhand"],
  "826": ["Dhanbad", "Jharkhand"],
  "827": ["Bokaro", "Jharkhand"],
  "828": ["Dhanbad", "Jharkhand"],
  "829": ["Ramgarh", "Jharkhand"],
  "831": ["Jamshedpur", "Jharkhand"],
  "832": ["Saraikela", "Jharkhand"],
  "833": ["Chaibasa", "Jharkhand"],
  "834": ["Ranchi", "Jharkhand"],
  "835": ["Ranchi", "Jharkhand"],
  "841": ["Chapra", "Bihar"],
  "842": ["Muzaffarpur", "Bihar"],
  "843": ["Muzaffarpur", "Bihar"],
  "844": ["Vaishali", "Bihar"],
  "845": ["Motihari", "Bihar"],
  "846": ["Darbhanga", "Bihar"],
  "847": ["Madhubani", "Bihar"],
  "848": ["Samastipur", "Bihar"],
  "851": ["Begusarai", "Bihar"],
  "852": ["Saharsa", "Bihar"],
  "853": ["Khagaria", "Bihar"],
  "854": ["Katihar", "Bihar"],
  "855": ["Kishanganj", "Bihar"],
};

/** Exact-pincode overrides where the 3-digit prefix would be misleading. */
const PIN6_OVERRIDE: Record<string, [string, IndianState]> = {
  "362520": ["Diu", "Dadra & Nagar Haveli and Daman & Diu"],
  "396210": ["Daman", "Dadra & Nagar Haveli and Daman & Diu"],
  "396230": ["Silvassa", "Dadra & Nagar Haveli and Daman & Diu"],
  "682555": ["Kavaratti", "Lakshadweep"],
};

export type PincodeLookup = {
  pincode: string;
  city: string | null;
  state: IndianState | null;
  /** How confident we are — drives the UI hint shown next to the field. */
  precision: "exact" | "district" | "state" | "unknown";
};

export function isValidPincode(pin: string): boolean {
  return /^[1-9][0-9]{5}$/.test(pin.trim());
}

export function lookupPincode(raw: string): PincodeLookup {
  const pin = raw.trim();
  const base: PincodeLookup = { pincode: pin, city: null, state: null, precision: "unknown" };
  if (!isValidPincode(pin)) return base;

  const exact = PIN6_OVERRIDE[pin];
  if (exact) return { pincode: pin, city: exact[0], state: exact[1], precision: "exact" };

  const district = PIN3_CITY[pin.slice(0, 3)];
  if (district) return { pincode: pin, city: district[0], state: district[1], precision: "district" };

  const state = PIN2_STATE[pin.slice(0, 2)];
  if (state) return { pincode: pin, city: null, state, precision: "state" };

  return base;
}

/**
 * Google (and most third-party address sources) spell the multi-word union
 * territories with "and" and use pre-rename district names. Fold those onto the
 * canonical list so a Places result lands on a value our rate cards recognise.
 */
const STATE_ALIASES: Record<string, IndianState> = {
  "jammu and kashmir": "Jammu & Kashmir",
  "andaman and nicobar islands": "Andaman & Nicobar Islands",
  "andaman and nicobar": "Andaman & Nicobar Islands",
  "dadra and nagar haveli and daman and diu": "Dadra & Nagar Haveli and Daman & Diu",
  "dadra and nagar haveli": "Dadra & Nagar Haveli and Daman & Diu",
  "daman and diu": "Dadra & Nagar Haveli and Daman & Diu",
  "nct of delhi": "Delhi",
  "national capital territory of delhi": "Delhi",
  "new delhi": "Delhi",
  pondicherry: "Puducherry",
  orissa: "Odisha",
  uttaranchal: "Uttarakhand",
  "tamilnadu": "Tamil Nadu",
};

export function normalizeStateName(raw: string | null | undefined): IndianState | null {
  if (!raw) return null;
  const value = raw.trim();
  const exact = INDIAN_STATES.find((s) => s.toLowerCase() === value.toLowerCase());
  if (exact) return exact;

  const key = value.toLowerCase().replace(/\s+/g, " ");
  if (STATE_ALIASES[key]) return STATE_ALIASES[key];

  // "Jammu & Kashmir" vs "Jammu and Kashmir" and stray punctuation.
  const loose = key.replace(/&/g, "and").replace(/[.,]/g, "").trim();
  if (STATE_ALIASES[loose]) return STATE_ALIASES[loose];

  const fuzzy = INDIAN_STATES.find(
    (s) => s.toLowerCase().replace(/&/g, "and").replace(/[.,]/g, "") === loose,
  );
  return fuzzy ?? null;
}

/**
 * GST state codes — the first two digits of every GSTIN.
 *
 * Worth checking at entry: a GSTIN whose state code disagrees with the address
 * state is one of the most common reasons an e-Way Bill is rejected, and it
 * surfaces at a check post rather than at booking.
 */
export const GST_STATE_CODES: Record<IndianState, string> = {
  "Jammu & Kashmir": "01",
  "Himachal Pradesh": "02",
  Punjab: "03",
  Chandigarh: "04",
  Uttarakhand: "05",
  Haryana: "06",
  Delhi: "07",
  Rajasthan: "08",
  "Uttar Pradesh": "09",
  Bihar: "10",
  Sikkim: "11",
  "Arunachal Pradesh": "12",
  Nagaland: "13",
  Manipur: "14",
  Mizoram: "15",
  Tripura: "16",
  Meghalaya: "17",
  Assam: "18",
  "West Bengal": "19",
  Jharkhand: "20",
  Odisha: "21",
  Chhattisgarh: "22",
  "Madhya Pradesh": "23",
  Gujarat: "24",
  "Dadra & Nagar Haveli and Daman & Diu": "26",
  Maharashtra: "27",
  Karnataka: "29",
  Goa: "30",
  Lakshadweep: "31",
  Kerala: "32",
  "Tamil Nadu": "33",
  Puducherry: "34",
  "Andaman & Nicobar Islands": "35",
  Telangana: "36",
  "Andhra Pradesh": "37",
  Ladakh: "38",
};

/** Distinct known cities for a state — powers the rate-card city dropdown. */
export function citiesForState(state: string): string[] {
  const set = new Set<string>();
  for (const [city, st] of Object.values(PIN3_CITY)) if (st === state) set.add(city);
  for (const [city, st] of Object.values(PIN6_OVERRIDE)) if (st === state) set.add(city);
  return [...set].sort((a, b) => a.localeCompare(b));
}

/**
 * Coarse freight zone. Rate cards are lane-based, but zones give us a sane
 * default transit estimate when a lane has no explicit row.
 */
export function zoneForState(state: string): "N" | "S" | "E" | "W" | "C" | "NE" {
  const map: Record<string, "N" | "S" | "E" | "W" | "C" | "NE"> = {
    Delhi: "N", Haryana: "N", Punjab: "N", Chandigarh: "N", "Himachal Pradesh": "N",
    "Jammu & Kashmir": "N", Ladakh: "N", "Uttar Pradesh": "N", Uttarakhand: "N", Rajasthan: "N",
    Karnataka: "S", "Tamil Nadu": "S", Kerala: "S", "Andhra Pradesh": "S", Telangana: "S",
    Puducherry: "S", Lakshadweep: "S",
    "West Bengal": "E", Odisha: "E", Bihar: "E", Jharkhand: "E", Sikkim: "E",
    "Andaman & Nicobar Islands": "E",
    Maharashtra: "W", Gujarat: "W", Goa: "W", "Dadra & Nagar Haveli and Daman & Diu": "W",
    "Madhya Pradesh": "C", Chhattisgarh: "C",
    Assam: "NE", "Arunachal Pradesh": "NE", Manipur: "NE", Meghalaya: "NE",
    Mizoram: "NE", Nagaland: "NE", Tripura: "NE",
  };
  return map[state] ?? "C";
}
