import type { Metadata } from "next";
import { PageHero, Section, SectionHead } from "@/components/marketing/PageHero";
import { Bullets, Callout, DataTable, DefList } from "@/components/marketing/Prose";
import { ButtonLink } from "@/components/ui/Button";
import { findTopic } from "@/lib/support";
import { EWAY_BILL_THRESHOLD } from "@/lib/validation";

const TOPIC = findTopic("mandatory-documentation");

export const metadata: Metadata = { title: TOPIC.title, description: TOPIC.blurb };

const inr = (n: number) => `₹${n.toLocaleString("en-IN")}`;

export default function Page() {
  return (
    <>
      <PageHero
        eyebrow="Support"
        title={TOPIC.title}
        lead="A consignment moves only as far as its paperwork allows. This is what has to be in the packet before a vehicle is loaded."
      />

      <Section>
        <SectionHead
          title="Always required"
          lead="These four travel with every commercial consignment, without exception."
        />
        <DefList
          items={[
            [
              "Tax invoice",
              "The commercial invoice against which the goods move. The invoice number is captured at booking and printed on the Lorry Receipt so the two can be reconciled at delivery.",
            ],
            [
              "Lorry Receipt (consignment note)",
              "Generated by us at booking. It carries the LRN, both parties, the declared goods, the box count and the freight terms. Two copies travel with the vehicle; the consignor keeps one.",
            ],
            [
              "Carton tags",
              "One tag per carton, each with its own barcode. Untagged cartons cannot be scanned at a hub, which means they cannot be traced if a box goes missing.",
            ],
            [
              "Consignor and consignee details",
              "Full name, address, PIN code and a reachable phone number for both ends. A wrong phone number is the single most common cause of a failed first delivery attempt.",
            ],
          ]}
        />
      </Section>

      <Section className="border-y border-line bg-surface">
        <SectionHead
          title="Required in specific cases"
          lead="Whether these apply depends on the goods, the value and the states involved."
        />
        <DataTable
          head={["Document", "When it applies", "Who issues it"]}
          rows={[
            [
              "E-way bill",
              `Movement of goods valued above ${inr(EWAY_BILL_THRESHOLD)}, inter-state and in most intra-state cases`,
              "Consignor, on the GST e-way bill portal",
            ],
            [
              "GSTIN",
              "Whenever either party is GST-registered — 15 characters, validated at booking",
              "Already held by the registered party",
            ],
            [
              "Delivery challan",
              "Movement that is not a sale: stock transfer, job work, goods on approval, returns",
              "Consignor",
            ],
            [
              "Packing list",
              "Multi-carton consignments where cartons hold different SKUs",
              "Consignor",
            ],
            [
              "MSDS / DG declaration",
              "Any hazardous or dangerous goods accepted under prior approval",
              "Manufacturer, countersigned by consignor",
            ],
            [
              "Drug licence copy",
              "Pharmaceutical and medical-device consignments",
              "Consignor's licensing authority",
            ],
            [
              "Insurance certificate",
              "Where carrier risk (FOV) is declined and the consignor insures separately",
              "Consignor's insurer",
            ],
            [
              "KYC (ID and address proof)",
              "Consignments booked by an individual rather than a registered business",
              "Consignor",
            ],
          ]}
          caption="Requirements follow central GST rules; individual states add their own transit formalities on some commodities. The booking desk flags anything extra for your lane."
        />
      </Section>

      <Section>
        <SectionHead title="How the e-way bill threshold works" />
        <Bullets
          items={[
            <>
              The {inr(EWAY_BILL_THRESHOLD)} threshold is on the{" "}
              <strong className="font-semibold text-ink">consignment value</strong>, which is the
              invoice value including tax — not the freight charge.
            </>,
            "A single vehicle carrying several consignments can require a bill for some and not others. Each consignment is assessed on its own value.",
            "Part-B of the bill needs the vehicle number, which we supply. Part-A is yours to file, because it declares your goods and your GSTIN.",
            "Bills expire on distance — roughly one day per 200 km by road. A bill raised too early can lapse mid-transit.",
            "We carry the number onto the Lorry Receipt. We do not generate e-way bills on your behalf.",
          ]}
        />

        <div className="mt-8 space-y-4">
          <Callout tone="warn" title="A missing e-way bill stops the vehicle, not just the box">
            Goods moving without a required bill can be detained and penalised at a checkpost, and
            the penalty attaches to the consignment value. Where a bill is required and absent, we
            hold the consignment at origin rather than load it.
          </Callout>
          <Callout title="Declare the goods accurately">
            The description on the Lorry Receipt is what a checkpost officer reads. A generic entry
            like &ldquo;goods&rdquo; or &ldquo;spares&rdquo; against a high-value invoice invites a
            physical inspection and a day of delay.
          </Callout>
        </div>
      </Section>

      <Section className="border-t border-line">
        <SectionHead
          title="Not sure what your lane needs?"
          lead="Send us the origin, destination, commodity and invoice value, and we will tell you exactly what to put in the packet."
        />
        <div className="flex flex-wrap gap-3">
          <ButtonLink href="/contact">Ask the ops desk</ButtonLink>
          <ButtonLink href="/faqs" variant="secondary">
            Browse FAQs
          </ButtonLink>
        </div>
      </Section>
    </>
  );
}
